mother(X,triton).
children(X,zeus).
grandmother(X,benthesikyme).
daughter(hermes,demeter).
sibling(hebe,triton).
father(X,apollo).
aunt(X,ares).
parent(hera,persephone).
grandfather(X,dinoysus).
sister(athena,hermes).
husband(X,rhea).
sibling(hephaestus,hebe).
grandmother(X,ilithyia).
aunt(X,ares).
sibling(X,Apollo).
wife(X,poseidon).
wife(demeter,hera).
daughter(X,hera).
son(trion,amphitrite).
wife(X,ares).